### ISSUE TITLE
Can no longer not specify version

### ISSUE THREAD

**Issue by fmc100** [loft-sh/devspace-plugin-loft#5]
Version is now required or there is an error.

Steps to repro:

1. Download Devspace
2. Try to add loft without a version
Expected:
it installs the latest
Actual:
```
[fatal]  error executing plugin binary, make sure the plugin binary is executable and returns a zero exit code when run without arguments:  => fork/exec /Users/*****/*****/plugin-binary: exec format error
```

**Comment by FabianKramm** [comment]
@fmc100 thanks for creating the issue! We renamed the repo which was not reflected in the binary name of the plugin, it should work now again

**Comment by fmc100** [comment]
works, thanks @FabianKramm!
